#ifndef TANNERDRAKE_DEV_H
#define TANNERDRAKE_DEV_H

#include "quantum.h"

#define LAYOUT( \
	KC_ESC,		 KC_F1, 	KC_F2, 	KC_F3, 		KC_F4, 	KC_F5, 	KC_F6, 		KC_F7, 	KC_F8, 	KC_F9, 		KC_F10, 	KC_F11, 	KC_F12, 		KC_HOME, 		KC_END, 	KC_PSCREEN, 	KC_PGUP, 		KC_PGDOWN, 		KC_DELETE, \
	KC_GRAVE,	 KC_1, 		KC_2, 	KC_3, 		KC_4, 	KC_5, 	KC_6, 		KC_7, 	KC_8, 	KC_9, 		KC_0, 		KC_MINUS, 	KC_EQUAL, 		KC_NO, 			KC_BSPACE, 	KC_NUMLOCK, 	KC_KP_SLASH, 	KC_KP_ASTERISK, KC_KP_MINUS, \
	KC_TAB, 	 KC_NO1, 	KC_Q, 	KC_W, 		KC_E, 	KC_R, 	KC_T, 		KC_Y, 	KC_U, 	KC_I, 		KC_O, 		KC_P, 		KC_LBRACKET, 	KC_RBRACKET, 	KC_BSLASH, 	KC_KP_7, 		KC_KP_8, 		KC_KP_9, 		KC_NO2, \
	KC_CAPSLOCK, KC_NO3, 	KC_A, 	KC_S, 		KC_D, 	KC_F, 	KC_G, 		KC_H, 	KC_J, 	KC_K, 		KC_L, 		KC_SCOLON, 	KC_QUOTE, 		KC_ENTER, 		KC_NO4, 		KC_KP_4, 		KC_KP_5, 		KC_KP_6, 		KC_KP_PLUS, \
	KC_LSHIFT, 	 KC_NO5, 	KC_Z, 	KC_X, 		KC_C, 	KC_V, 	KC_B, 		KC_N, 	KC_M, 	KC_COMMA, 	KC_DOT, 	KC_SLASH, 	KC_NO6, 			KC_RSHIFT, 		KC_UP, 		KC_KP_1, 		KC_KP_2, 		KC_KP_3, 		KC_NO7, \
	KC_LCTRL, 	 KC_LWIN, 	KC_NO8, 	KC_LALT, 	KC_NO9, 	KC_NO10, 	KC_SPACE, 	KC_NO11, 	KC_NO12, 	KC_NO13, 		KC_RALT, 	KC_RALT2, 	KC_RCTRL, 		KC_LEFT, 		KC_DOWN, 	KC_RIGHT, 		KC_KP_0, 		KC_KP_DOT, 		KC_KP_ENTER \
) { \
	{ KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_HOME, KC_END, KC_PSCREEN, KC_PGUP, KC_PGDOWN, KC_DELETE }, \
	{ KC_GRAVE, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINUS, KC_EQUAL, KC_NO, 	KC_BSPACE, KC_NUMLOCK, KC_KP_SLASH, KC_KP_ASTERISK, KC_KP_MINUS }, \
	{ KC_TAB, KC_NO1, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRACKET, KC_RBRACKET, KC_BSLASH, KC_KP_7, KC_KP_8, KC_KP_9, KC_NO2 }, \
	{ KC_CAPSLOCK, KC_NO3, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCOLON, KC_QUOTE, KC_ENTER, KC_NO4, KC_KP_4, KC_KP_5, KC_KP_6, KC_KP_PLUS }, \
	{ KC_LSHIFT, KC_NO5, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMMA, KC_DOT, KC_SLASH, KC_NO6, KC_RSHIFT, KC_UP, KC_KP_1, KC_KP_2, KC_KP_3, KC_NO7 }, \
	{ KC_LCTRL, KC_LWIN, KC_NO8, KC_LALT, KC_NO9, KC_NO10, KC_SPACE, KC_NO11, KC_NO12, KC_NO13,	KC_RALT, KC_RALT2, KC_RCTRL, KC_LEFT, KC_DOWN, 	KC_RIGHT, KC_KP_0, KC_KP_DOT, KC_KP_ENTER }, \
}

#endif
