#ifndef KEYBOARDS_CHIBIOS_TEST_TANNERDRAKE_DEV_CONFIG_H_
#define KEYBOARDS_CHIBIOS_TEST_TANNERDRAKE_DEV_CONFIG_H_

#include "../config.h"

#endif /* KEYBOARDS_CHIBIOS_TEST_TANNERDRAKE_DEV_CONFIG_H_ */
